### ISSUE TITLE
get_dirty_fields fails if check_m2m is not None

### ISSUE THREAD

**Issue by BogdanL** [romgar/django-dirtyfields#98]
Line 101 of dirtyfields.py
`modified_m2m_fields = compare_states(check_m2m, self._original_m2m_state, self.compare_function)`

should be 

`modified_m2m_fields = compare_states(self._as_dict_m2m(), self._original_m2m_state, self.compare_function)`

**Comment by romgar** [comment]
Hi @BogdanL !

Can you show me a code example of how you use this option?

Tracking m2m fields is a bit different than the rest of the fields in `django-dirtyfields`. The original idea of this package is to track a difference between your current instance in memory with the instance that has been previously saved in the database.

As m2m fields are directly saved to the database (overtime you call `.add()` for example), you can't really have an in-memory instance different than the one in the db.

I have tried to explain it in the documentation (http://django-dirtyfields.readthedocs.io/en/develop/#checking-many-to-many-fields), but if you think it's unclear, feel free to propose a better wording. 

And if I missed/misunderstood your current situation, please tell me.

**Comment by romgar** [comment]
I close it for now. Feel free to reopen if needed.

**Comment by techdragon** [comment]
@romgar can you reopen this? I'm looking over the documentation and the source code and I can definitely see something that I find unclear. The example for M2M tracking, and the tests, use an explicit dictionary created and passed to the `get_dirty_fields` function. however in addition to the `self._as_dict` function there is clearly a `self._as_dict_m2m` which would when combined with some git history digging ( https://github.com/romgar/django-dirtyfields/commit/ac1d1e27b309da6045be8ac180d891454020dde5 ) looks like it was originally used so that you didn't have to explicitly say what M2M change you were looking for. 

Since the example `tm.get_dirty_fields(check_m2m={'m2m_field': set([tm2.id])})` and the follow up example `tm.get_dirty_fields(check_m2m={'m2m_field': set(["dummy_value])})` both _imply_ that I have to know what the original state is in order to track changes, the current explanation feels inadequate.

It would be good to clarify the current code, and potentially to document the previous behaviour via `_as_dict_m2m`. 

This came up because I'm working on a mixin that is meant to do something if the fields are dirty, and since its a mixin, I dont know what the model will be, I cant make up the dictionary like the examples show, and the original "just works" behaviour would be better. Just like how you currently warn that checking M2M is potentially slow, it seems sensible to just warn that "autodetecting M2M is _very_ slow" and still show me how to do it since it at least looks like it should work if I were to do something similar to this `my_model_object.get_dirty_fields(check_m2m=my_model_object._as_dict_m2m))`
